INSERT INTO character (first_name, family_name, short_name, nickname)
 VALUES
    ('Eddard', 'Stark', 'Ned', ''),
    ('Petyr', 'Baelish', '', '"Littlefinger"'),
    ('Sandor', 'Clegane', '', '"The Hound"'),
    ('Robert', 'Baratheon', '',''),
    ('Jaime', 'Lannister', '',''),
    ('Catelyn', 'Stark', '',''),
    ('Cersei', 'Lannister', '',''),
    ('Daenerys', 'Targaryen', '',''),
    ('Jorah', 'Mormont', '',''),
    ('Viserys', 'Targaryen', '',''),
    ('Jon', 'Snow', '',''),
    ('Sansa', 'Stark', '',''),
    ('Arya', 'Stark', '',''),
    ('Robb', 'Stark', '',''),
    ('Theon', 'Greyjoy', '',''),
    ('Bran', 'Stark', '',''),
    ('Joffrey', 'Baratheon', '',''),
    ('Tyrion', 'Lannister', '',''),
    ('Tywin', 'Lannister', '',''),
    ('Davos', 'Seaworth', '',''),
    ('Samwell', 'Tarly', '',''),
    ('Margaery', 'Tyrell', '',''),
    ('Stannis', 'Baratheon', '',''),
    ('Jeor', 'Mormont', '',''),
    ('Talisa', 'Maegyr', '',''),
    ('Tormund', 'Giantsbane', '',''),
    ('Brienne', 'Tarth', '',''),
    ('Ramsay', 'Bolton', '',''),
    ('Ellaria', 'Sand', '',''),
    ('Daario', 'Naharis', '',''),
    ('Jaqen', 'H''ghar', '',''),
    ('Tommen', 'Bratheon', '',''),
    ('Roose', 'Bolton', '',''),
    ('','', '', 'The High Sparrow'),
    ('Melisandre', '','',''),
    ('Missandei', '','',''),
    ('Bronn', '','',''),
    ('Varys', '','',''),
    ('Shae', '','',''),
    ('Ygritte', '','',''),
    ('Gilly', '','',''),
    ('Gendry', '','',''),
    ('Drogo', '','','');